baseURL = "https://simple-smoothies.netlify.app/"
languageCode = "en-us"
title = "Simple Smoothies"
theme = "simple_smoothies"
googleAnalytics = "UA-123-45"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/page/about/"

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"

[Params]
    mainSections = ["post"]
    intro = true
    headline = "My headline"
    description = "The biggest collection of smoothie recipes in the world"
    github = "https://github.com/XXX"
    twitter = "https://twitter.com/XXX"
    email = "XXX@example.com"
    opengraph = true
    shareTwitter = true
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:filename/"
